// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luqkxmizxqvrurufgwdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1cWt4bWl6eHF2cnVydWZnd2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDgxNDEsImV4cCI6MjA2MzI4NDE0MX0.bItzM47iYnLYNcZ-7EVwpd49fJnnZQ_0Hdo487qXEbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);